## This workflow is triggered on pushes to the main branch and deploys the application
# to a remote server using SSH and Docker Compose.

name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/forum-api
            git pull origin main
            npm install
            npm run migrate up
            pm2 describe forum-api > /dev/null 2>&1 && pm2 restart forum-api || pm2 start npm --name forum-api -- run start
